# Generated by Django 4.2.16 on 2025-07-29 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('election_date', models.DateField()),
                ('election_type', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=2)),
                ('jurisdiction', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VoterRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voter_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('address', models.TextField()),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('party_affiliation', models.CharField(blank=True, max_length=50)),
                ('social_media', models.JSONField(blank=True, default=dict)),
                ('employment', models.JSONField(blank=True, default=dict)),
                ('data_source', models.CharField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_voters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoterEngagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('engagement_type', models.CharField(choices=[('phone_call', 'Phone Call'), ('door_knock', 'Door Knock'), ('text_message', 'Text Message'), ('email', 'Email'), ('direct_mail', 'Direct Mail'), ('social_media', 'Social Media'), ('event', 'Event')], max_length=50)),
                ('campaign_id', models.UUIDField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('response_data', models.JSONField(blank=True, default=dict)),
                ('engagement_date', models.DateTimeField(auto_now_add=True)),
                ('engaged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_engagements', to=settings.AUTH_USER_MODEL)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagements', to='voter_data.voterrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('voted', models.BooleanField(default=False)),
                ('vote_method', models.CharField(blank=True, max_length=50)),
                ('vote_date', models.DateField(blank=True, null=True)),
                ('precinct', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voter_data', to='voter_data.election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='election_data', to='voter_data.voterrecord')),
            ],
        ),
        migrations.CreateModel(
            name='EarlyVoteRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('ballot_status', models.CharField(blank=True, max_length=50)),
                ('return_method', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_votes', to='voter_data.election')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='early_votes', to='voter_data.voterrecord')),
            ],
        ),
        migrations.AddIndex(
            model_name='voterrecord',
            index=models.Index(fields=['voter_id'], name='voter_data__voter_i_ca7596_idx'),
        ),
        migrations.AddIndex(
            model_name='voterrecord',
            index=models.Index(fields=['state', 'zip_code'], name='voter_data__state_8b8a56_idx'),
        ),
        migrations.AddIndex(
            model_name='voterrecord',
            index=models.Index(fields=['account_owner'], name='voter_data__account_caaffa_idx'),
        ),
        migrations.AddIndex(
            model_name='voterengagement',
            index=models.Index(fields=['voter', 'engagement_date'], name='voter_data__voter_i_694a67_idx'),
        ),
        migrations.AddIndex(
            model_name='voterengagement',
            index=models.Index(fields=['campaign_id'], name='voter_data__campaig_b39cc1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='electiondata',
            unique_together={('voter', 'election')},
        ),
        migrations.AlterUniqueTogether(
            name='earlyvoterecord',
            unique_together={('voter', 'election')},
        ),
    ]
