# Generated by Django 4.2.16 on 2025-07-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='electiondata',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='election',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='election',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='electiondata',
            name='data_type',
            field=models.CharField(choices=[('location', 'Voting Location'), ('ballot_type', 'Ballot Type'), ('ballot_choice', 'Ballot Choice'), ('voted', 'Voted (Boolean)')], default='voted', max_length=50),
        ),
        migrations.AddField(
            model_name='electiondata',
            name='value',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='contact_phone_unknown1',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_city_council_district',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_city_incorporation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_city_limits',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_city_municipality',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_city_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_city_school_district',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_county_career_center',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_county_commissioner_precinct',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_county_community_college',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_county_constable_precinct',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_county_district_attorney',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_county_education_service_center',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_county_exempted_village_school_district',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_county_first_class_school',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_county_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_county_library_district',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_county_local_school_district',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_county_mass_transit_authority',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_county_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_county_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_county_representational_school',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_county_sanitary',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_county_school',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_county_school_district',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_county_sub_school_district',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_county_supervisory',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_county_technical_college',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_county_township',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_county_village',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_county_ward',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_county_water_district_01',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_county_water_district_02',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_court_appeallate',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_court_county',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_court_municipal',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_federal_congressional',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_level',
            field=models.CharField(blank=True, choices=[('federal', 'Federal'), ('state', 'State'), ('county', 'County'), ('city', 'City'), ('local', 'Local'), ('special_district', 'Special District')], max_length=20),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_state',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_state_board_of_education',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_state_circuit_court',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_state_court_of_appeals',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_state_district_combo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_state_juristidction',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_state_legislative_lower',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_state_legislative_upper',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_state_lower',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_state_multijurisdictional_judge',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='district_state_upper',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='file_origin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Address verification status'),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='mail_address1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='mail_address2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='mail_change_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='mail_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='mail_country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='mail_postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='mail_standardized',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='mail_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='mail_zip4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='mail_zip5',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='mailing_address',
            field=models.TextField(blank=True, help_text='Full mailing address'),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='office_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='person_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='person_gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='person_name_first',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='person_name_last',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='person_name_middle',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='person_name_prefix',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='person_name_suffix',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='residence_address1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='residence_address2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='residence_address_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='residence_country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='residence_effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='residence_part_city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='residence_part_house_direction',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='residence_part_house_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='residence_part_state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='residence_part_street_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='residence_part_street_suffix',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='residence_part_street_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='residence_part_unit_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='residence_part_unit_type',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='residence_part_zip4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='residence_part_zip5',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='residence_postal_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='residence_standardized',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='residential_address',
            field=models.TextField(blank=True, help_text='Full residential address'),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='voter_absentee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='voter_county',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='voter_political_party',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='voter_precinct_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='voter_precinct_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='voter_precinct_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='voter_precinct_split',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='voter_registration_application_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='voter_registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='voter_registration_permanent_absentee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='voter_registration_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='voter_registration_status_reason',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='voter_registration_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='voterrecord',
            name='voter_vuid',
            field=models.CharField(blank=True, help_text='Primary voter unique identifier', max_length=50),
        ),
        migrations.AlterField(
            model_name='election',
            name='election_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='election_type',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('primary', 'Primary'), ('special', 'Special'), ('referendum', 'Referendum')], max_length=50),
        ),
        migrations.AlterField(
            model_name='election',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='election',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='voterrecord',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voterrecord',
            name='data_source',
            field=models.CharField(default='csv_upload', max_length=100),
        ),
        migrations.AlterField(
            model_name='voterrecord',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='voterrecord',
            name='voter_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='electiondata',
            unique_together={('voter', 'election', 'data_type')},
        ),
        migrations.AddIndex(
            model_name='voterrecord',
            index=models.Index(fields=['voter_vuid'], name='voter_data__voter_v_e39611_idx'),
        ),
        migrations.AddIndex(
            model_name='voterrecord',
            index=models.Index(fields=['residence_part_state', 'residence_part_zip5'], name='voter_data__residen_c8207a_idx'),
        ),
        migrations.AddIndex(
            model_name='voterrecord',
            index=models.Index(fields=['district_level', 'office_type'], name='voter_data__distric_b18206_idx'),
        ),
    ]
