# Generated by Django 4.2.16 on 2025-07-30 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('canvassing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='walklist',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_walk_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walklist',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walk_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_questionnaires', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='canvassresponse',
            name='questionnaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='canvassing.questionnaire'),
        ),
        migrations.AddField(
            model_name='canvassresponse',
            name='volunteer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvass_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='canvassresponse',
            name='walk_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='canvassing.walklist'),
        ),
        migrations.AlterUniqueTogether(
            name='canvassresponse',
            unique_together={('questionnaire', 'voter_id', 'walk_list')},
        ),
    ]
