# Generated by Django 4.2.16 on 2025-07-29 23:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Integration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('segment', 'Segment'), ('mailchimp', 'Mailchimp'), ('twilio', 'Twilio'), ('facebook', 'Facebook'), ('twitter', 'Twitter/X'), ('tiktok', 'TikTok'), ('snapchat', 'Snapchat'), ('fullcontact', 'FullContact'), ('spokeo', 'Spokeo'), ('zoominfo', 'ZoomInfo')], max_length=50)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('oauth_token', models.TextField(blank=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
