# Generated by Django 4.2.16 on 2025-07-29 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='integration',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='integration',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_integrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='integration',
            unique_together={('account', 'service')},
        ),
    ]
